# generate_data.py
import os

german_samples = [
    "Das Wetter ist heute wunderschön.",
    "Ich liebe Programmierung und maschinelles Lernen.",
    "Um wie viel Uhr ist das Meeting morgen?",
    "Können Sie mir bei diesem Problem helfen?",
    "Das neue Restaurant hat ausgezeichnetes Essen.",
    "Ich lerne Python-Programmierung.",
    "Der Film war wirklich interessant.",
    "Wie war dein Wochenende?",
    "Ich muss dieses Projekt bald abschließen.",
    "Das Buch liegt auf dem Tisch.",
    "Am Samstagmorgen wachte ich früh auf, weil ich ein wichtiges Meeting mit meinem Chef hatte. Nachdem ich aufgestanden war, machte ich mir einen Kaffee und aß ein kleines Frühstück. Während des Frühstücks dachte ich nach, wie ich das Projekt verbessern könnte, an dem wir seit Wochen arbeiten. Es war ein anspruchsvolles Projekt, aber ich war zuversichtlich, dass wir es erfolgreich abschließen würden.",
    "Am Montagmorgen war ich früh aufgestanden, weil ich ein wichtiges Meeting mit meinem Chef hatte. Nachdem ich aufgestanden war, machte ich mir einen Kaffee und aß ein kleines Frühstück. Während des Frühstücks dachte ich nach, wie ich das Projekt verbessern könnte, an dem wir seit Wochen arbeiten. Es war ein anspruchsvolles Projekt, aber ich war zuversichtlich, dass wir es erfolgreich abschließen würden.",
    "Ich zog mich an und fuhr mit dem Auto zur Arbeit. Auf dem Weg zur Arbeit hörte ich Musik, um mich zu entspannen. Als ich im Büro ankam, begrüßte mich mein Kollege Tom, der bereits am Computer arbeitete. Wir besprachen die letzten Details des Projekts und machten uns dann daran, die Aufgaben zu verteilen. Ich erklärte ihm, wie er den Bericht fertigstellen sollte, und gab ihm einige Hinweise. Während der Arbeit unterhielten wir uns über verschiedene Themen, darunter auch unsere Hobbys und Urlaubserlebnisse.",
    "Nachdem wir den Bericht abgeschlossen hatten, machten wir eine kurze Pause und tranken einen Tee. Wir beschlossen, später ein weiteres Meeting zu organisieren, um die nächsten Schritte zu besprechen.",
    "Am Mittwochabend war ich müde und ging ins Bett. Ich las ein Buch und schlief um 10 Uhr. Am Donnerstag früh war ich wieder früh aufgestanden, weil ich ein wichtiges Meeting mit meinem Chef hatte. Nachdem ich aufgestanden war, machte ich mir einen Kaffee und aß ein kleines Frühstück. Während des Frühstücks dachte ich nach, wie ich das Projekt verbessern könnte, an dem wir seit Wochen arbeiten. Es war ein anspruchsvolles Projekt, aber ich war zuversichtlich, dass wir es erfolgreich abschließen würden.",
    "Am Freitagabend ging ich mit meinen Freunden ins Kino. Wir sahen einen neuen Actionfilm, der sehr spannend war. Nachdem wir das Kino verlassen hatten, gingen wir in ein Restaurant und tranken ein Glas Wein. Wir beschlossen, am nächsten Wochenende ein weiteres Kino zu besuchen.",
    "Ich spreche drei Sprachen fließend.",
    "Das Konzert beginnt um 20 Uhr.",
    "Ich freue mich auf die Ferien.",
    "Der Computer muss repariert werden.",
    "Was ist deine Lieblingsfarbe?",
    "Der Zug kommt in 10 Minuten.",
    "Ich lese gerne Science-Fiction-Bücher.",
    "Der Garten muss bewässert werden.",
    "Kannst du mir bitte das Salz reichen?",
    "Der Wetterbericht sagt Regen voraus.",
    "Ich gehe später ins Fitnessstudio.",
    "Die Präsentation war sehr erfolgreich.",
    "Wie ist deine Telefonnummer?",
    "Der Kaffee ist zu heiß.",
    "Ich muss Lebensmittel einkaufen.",
    "Das Kino ist voll.",
    "Wie buchstabiert man deinen Namen?",
    "Das Museum ist montags geschlossen.",
    "Ich lerne für die Prüfung.",
    "Das Restaurant ist ausgebucht.",
    "Was ist die Hauptstadt von Frankreich?",
    "Der Verkehr ist heute stark.",
    "Ich lerne Gitarre spielen.",
    "Die Bibliothek hat viele Bücher.",
    "Kannst du bitte langsamer sprechen?",
    "Es wird kälter.",
    "Ich werde meine Familie besuchen.",
    "Das Meeting beginnt in 5 Minuten.",
    "Was ist dein Lieblingsfilm?",
    "Der Computer läuft langsam.",
    "Ich muss telefonieren.",
    "Der Park ist im Frühling schön.",
    "Wie lange dauert der Film?",
    "Das Restaurant serviert gutes Essen.",
    "Ich suche meine Schlüssel.",
    "Der Zug hat Verspätung.",
    "Wie ist deine E-Mail-Adresse?",
    "Das Wetter ist heute perfekt.",
    "Ich fahre ans Meer.",
    "Das Buch ist sehr interessant.",
    "Die Katze schläft auf dem Sofa.",
    "Ich trinke gerne grünen Tee.",
    "Der Supermarkt öffnet um 8 Uhr.",
    "Mein Auto ist in der Werkstatt.",
    "Die Blumen im Garten blühen.",
    "Wir haben nächste Woche Urlaub.",
    "Das Haus braucht einen neuen Anstrich.",
    "Die Kinder spielen im Garten.",
    "Der Kuchen schmeckt sehr gut.",
    "Ich habe heute viel zu tun.",
    "Die Sonne scheint hell.",
    "Der Bus ist pünktlich.",
    "Wir treffen uns um 14 Uhr.",
    "Das Fenster ist offen.",
    "Die Musik ist zu laut.",
    "Ich brauche neue Schuhe.",
    "Der Himmel ist blau.",
    "Das Essen ist fertig.",
    "Die Party war großartig.",
    "Ich habe Kopfschmerzen.",
    "Der Drucker funktioniert nicht.",
    "Die Rechnung bitte.",
    "Das Paket kommt morgen an.",
    "Ich mag italienisches Essen.",
    "Die Straße ist gesperrt.",
    "Der Hund bellt laut.",
    "Das Telefon klingelt.",
    "Ich bin müde von der Arbeit.",
    "Die Tür ist verschlossen.",
    "Das Radio spielt gute Musik.",
    "Ich brauche einen Regenschirm.",
    "Der Wind ist stark heute.",
    "Das Geschäft schließt um 20 Uhr.",
    "Die Ampel ist rot.",
    "Ich habe einen Termin beim Arzt.",
    "Das Wasser ist kalt.",
    "Die Zeitung kommt jeden Morgen.",
    "Ich spreche gerne Deutsch.",
    "Der Aufzug ist kaputt.",
    "Das Mittagessen war lecker.",
    "Die Uhr geht nach.",
    "Ich liebe Schokolade.",
    "Der Schlüssel ist verloren.",
    "Das Licht ist aus.",
    "Die Post ist da.",
    "Ich brauche Hilfe.",
    "Der Stau ist lang.",
    "Das Bett ist gemacht.",
    "Die Suppe ist heiß.",
    "Ich habe Hunger.",
    "Der Fernseher ist neu.",
    "Das Handy ist ausgeschaltet.",
    "Die Rechnung ist bezahlt.",
    "Ich gehe spazieren.",
    "Der Kühlschrank ist leer.",
    "Das Geschenk ist verpackt.",
    "Die Heizung läuft.",
    "Ich bin erkältet.",
    "Der Termin ist bestätigt.",
    "Das Zimmer ist aufgeräumt.",
    "Die Batterie ist leer.",
    "Ich warte auf den Bus.",
    "Der Kaffee ist fertig.",
    "Das Fenster ist zu.",
    "Die Wäsche ist gewaschen.",
    "Ich bin beschäftigt.",
    "Der Computer startet nicht.",
    "Das Eis schmilzt.",
    "Die Tasse ist voll.",
    "Ich bin glücklich.",
    "Der Regen hört auf.",
    "Das Brot ist frisch.",
    "Die Sonne geht unter.",
    "Ich bin nervös.",
    "Der Zug ist voll.",
    "Das Wetter ändert sich.",
    "Die Blumen sind schön.",
    "Ich bin spät dran.",
    "Der Film fängt an.",
    "Das Telefon ist stumm.",
    "Die Party beginnt.",
    "Ich bin bereit.",
    "Der Schnee fällt.",
    "Das Auto ist sauber.",
    "Die Zeit vergeht schnell.",
    "Ich bin hungrig.",
    "Der Mond scheint hell.",
    "Das Haus ist groß.",
    "Die Musik spielt.",
    "Ich bin müde.",
    "Der Tag ist lang.",
    "Das Leben ist schön.",
    "Die Nacht ist still.",
    "Ich bin zufrieden.",
    "Der Sommer ist heiß.",
    "Das Meer ist blau.",
    "Die Luft ist frisch.",
    "Ich bin optimistisch.",
    "Der Winter ist kalt.",
    "Das Gras ist grün.",
    "Die Stadt ist laut.",
    "Ich bin kreativ.",
    "Der Himmel ist grau.",
    "Das Wasser ist klar.",
    "Die Straße ist lang.",
    "Ich bin produktiv.",
    "Der Baum ist hoch.",
    "Das Kind lacht.",
    "Die Sonne scheint.",
    "Ich bin motiviert.",
    "Der Vogel singt.",
    "Das Lied ist schön.",
    "Die Blume blüht.",
    "Ich bin konzentriert.",
    "Der Wald ist dunkel.",
    "Das Feuer brennt.",
    "Die Wolken ziehen.",
    "Ich bin entspannt.",
    "Der Berg ist steil.",
    "Das Tal ist tief.",
    "Die Welle ist groß.",
    "Ich bin vorbereitet.",
    "Der Fluss fließt.",
    "Das Boot schwimmt.",
    "Die Brücke ist lang.",
    "Ich bin organisiert.",
    "Der Wind weht.",
    "Das Blatt fällt.",
    "Die Tür öffnet sich.",
    "Ich bin fokussiert.",
    "Der Stern leuchtet.",
    "Das Herz schlägt.",
    "Die Uhr tickt.",
    "Ich bin aktiv.",
    "Der Weg ist weit.",
    "Das Ziel ist nah.",
    "Die Zeit läuft.",
    "Ich bin positiv."
]

spanish_samples = [
    "El clima está hermoso hoy.",
    "Me encanta la programación y el aprendizaje automático.",
    "¿A qué hora es la reunión mañana?",
    "¿Puedes ayudarme con este problema?",
    "El nuevo restaurante tiene excelente comida.",
    "Estoy aprendiendo programación en Python.",
    "La película fue realmente interesante.",
    "¿Cómo estuvo tu fin de semana?",
    "Necesito terminar este proyecto pronto.",
    "El libro está sobre la mesa.",
    "Desde que era pequeño, siempre he pensado mucho en el futuro. Me preguntaba qué quería ser, qué tipo de vida deseaba tener, y qué camino debía tomar. Cuando tenía ocho años, soñaba con ser astronauta. Me fascinaba el espacio, las estrellas y los planetas. Veía documentales sobre el universo y me imaginaba viajando por el cosmos.",
    "Pero con el tiempo, mis intereses fueron cambiando. Empecé a interesarme por la tecnología y los computadores. Pasaba horas frente a la pantalla, aprendiendo cómo funcionaban los programas. Descubrí que me gustaba resolver problemas y crear cosas nuevas. Así fue como nació mi sueño de convertirme en desarrollador de software.",
    "En la secundaria, tomé clases de informática. Mis profesores me motivaron mucho porque veían que tenía talento. También participé en un club de programación. Allí aprendí a trabajar en equipo, a comunicarme mejor y a colaborar con otros estudiantes. Hicimos proyectos interesantes, como crear una app para organizar tareas escolares.",
    "Durante ese tiempo, me di cuenta de que quería estudiar Ingeniería Informática. Así que me esforcé mucho para entrar en una buena universidad. Cuando logré ser aceptado, me sentí muy feliz y orgulloso. En la universidad, conocí a personas apasionadas por la tecnología como yo. Estudiamos asignaturas como algoritmos, bases de datos, redes y desarrollo web.",
    "Mi materia favorita fue el desarrollo web. Disfrutaba mucho diseñar interfaces y construir sitios funcionales. Pude desarrollar varias páginas web para proyectos académicos. Incluso ayudé a una pequeña tienda local a tener su propia página en línea. Esa experiencia me mostró cómo la tecnología puede tener un impacto real.",
    "Además de estudiar, también hice prácticas profesionales. Trabajé como pasante en una empresa de tecnología. Allí aprendí cómo se trabaja en un entorno profesional. Tuve la oportunidad de colaborar en proyectos reales y de recibir retroalimentación de expertos. Fue una etapa muy valiosa para mi crecimiento.",
    "Ahora que estoy por terminar la carrera, estoy pensando en el futuro. Quiero encontrar un trabajo donde pueda seguir aprendiendo y aportar mis conocimientos. Sueño con trabajar en una empresa innovadora, desarrollando soluciones que ayuden a la sociedad. También quiero seguir estudiando, tal vez hacer una maestría en inteligencia artificial. Me interesa mucho cómo las máquinas pueden aprender y tomar decisiones.",
    "Además, tengo el sueño de crear mi propia startup algún día. Quisiera fundar una empresa que ofrezca productos digitales útiles y accesibles. Sé que no será fácil, pero me emociona la idea de emprender. También me gustaría viajar a otros países y conocer diferentes culturas tecnológicas. Por eso, estoy estudiando inglés y practicando todos los días.",
    "Mis planes no terminan ahí. Quiero devolver a la comunidad lo que he aprendido. Me gustaría ser mentor de jóvenes interesados en la tecnología. Participar en eventos, dar charlas y motivar a otros sería muy gratificante. Creo que compartir el conocimiento es una forma de crecer juntos.",
    "En resumen, tengo muchos sueños y metas. Algunos son a corto plazo, como conseguir un buen trabajo. Otros son a largo plazo, como crear mi propia empresa. Lo importante es que cada día doy un paso hacia mis objetivos. No tengo miedo al fracaso, porque sé que de los errores también se aprende."
]

korean_samples = [
    "오늘 날씨가 정말 좋습니다.",
    "프로그래밍과 기계학습을 좋아합니다.",
    "내일 회의는 몇 시인가요?",
    "이 문제를 도와주실 수 있나요?",
    "새로운 레스토랑의 음식이 훌륭합니다.",
    "파이썬 프로그래밍을 배우고 있습니다.",
    "영화가 정말 재미있었습니다.",
    "주말은 어땠나요?",
    "이 프로젝트를 빨리 끝내야 합니다.",
    "책이 테이블 위에 있습니다.",
    "오늘 아침, 나는 일찍 일어나서 운동을 시작했습니다. 운동을 마친 후, 간단한 아침 식사를 준비했어요. 아침에는 보통 토스트와 계란, 그리고 커피를 먹습니다. 그 후, 나는 컴퓨터를 켜고 이메일을 확인했습니다. 오늘은 중요한 회의가 있어서 미리 준비해야 했어요.",
    "오전에는 회사에서 프로젝트에 대한 회의를 진행했습니다. 회의에서는 여러 부서가 참여하여 각자의 의견을 나누었고, 새로운 마케팅 전략을 논의했습니다. 나는 이 프로젝트에 대한 아이디어를 제시하며 팀원들과 협력하여 문제를 해결하는 방법에 대해 논의했습니다.",
    "점심 시간에는 동료들과 함께 근처의 레스토랑에 가서 맛있는 음식을 먹었습니다. 오늘 점심은 불고기 덮밥이었어요. 정말 맛있었고, 다들 즐거운 시간을 보냈습니다.",
    "오후에는 다시 사무실로 돌아와서 작업을 계속했어요. 특히, 데이터 분석을 통해 우리가 진행 중인 프로젝트의 진행 상황을 점검했습니다. 그리고 오후 4시쯤, 회의에서 나온 피드백을 바탕으로 보고서를 작성하기 시작했습니다.",
    "오후에는 다시 사무실로 돌아와서 작업을 계속했어요. 특히, 데이터 분석을 통해 우리가 진행 중인 프로젝트의 진행 상황을 점검했습니다. 그리고 오후 4시쯤, 회의에서 나온 피드백을 바탕으로 보고서를 작성하기 시작했습니다."
    "퇴근 후, 나는 집에 가서 가족과 함께 저녁을 먹었습니다. 오늘 저녁은 갈비찜과 밥, 그리고 김치였어요. 가족들과 이야기를 나누며 하루를 마무리하는 시간이 너무 소중하게 느껴졌습니다.",
    "교육은 개인과 사회의 발전에 있어서 핵심적인 역할을 합니다. 지식과 기술을 습득함으로써 사람들은 더 나은 미래를 준비할 수 있으며, 자신의 능력을 최대한 발휘할 수 있습니다. 특히 현대 사회에서는 변화의 속도가 빠르기 때문에 평생 교육의 중요성이 더욱 강조되고 있습니다. 학교 교육뿐만 아니라 온라인 강의, 직업 훈련 등 다양한 방식으로 학습 기회를 제공함으로써 모두가 교육의 혜택을 누릴 수 있어야 합니다.",
    "또한 교육은 사회적 평등을 실현하는 데 중요한 수단이기도 합니다. 교육을 통해 빈곤의 악순환을 끊고 더 나은 삶을 추구할 수 있는 길이 열립니다. 이를 위해 정부와 사회는 교육 기회의 형평성을 보장하고, 경제적 어려움이나 지역적 격차로 인해 교육에서 소외되는 이들이 없도록 해야 합니다. 마지막으로 교육은 인격 형성과 공동체 의식을 키우는 데 중요한 역할을 하며, 더 나은 사회를 만들기 위한 기초가 됩니다.",
    "어릴 때부터 나는 항상 미래에 대해 많은 생각을 했다. 나는 어떤 사람이 되고 싶은지, 어떤 일을 하고 싶은지 자주 상상하곤 했다. 처음에는 경찰이 되고 싶었다. 범죄를 막고 사람들을 도와주는 모습이 멋져 보였기 때문이다. 하지만 시간이 지나면서 나는 나에게 맞는 다른 길을 찾게 되었다.",
    "중학교에 들어가면서 나는 컴퓨터에 흥미를 가지게 되었다. 처음에는 단순히 게임을 좋아해서 컴퓨터를 자주 사용했지만, 점점 더 컴퓨터의 구조와 프로그램에 관심이 생겼다. 그래서 나는 고등학교에서 정보 과목을 열심히 공부하기로 마음먹었다. 선생님께서는 내가 컴퓨터에 재능이 있다고 칭찬해 주셨다. 그 말은 내게 큰 용기가 되었다.",
    "고등학교 시절 나는 프로그래밍 동아리에 가입했다. 그곳에서 나는 친구들과 함께 프로젝트를 하며 팀워크를 배웠다. 함께 문제를 해결하고, 코드를 수정하면서 많은 성장을 할 수 있었다. 대회에도 참가했는데, 비록 1등은 못 했지만 값진 경험이었다. 그 경험 덕분에 나는 IT 분야로 진로를 결정하게 되었다.",
    "대학교에서는 컴퓨터공학을 전공하기로 했다. 입학 후 나는 다양한 과목을 수강하며 새로운 지식을 쌓았다. 데이터베이스, 네트워크, 인공지능 등 흥미로운 주제가 많았다. 특히 웹 개발 수업이 재미있어서, 나는 웹 개발자를 꿈꾸게 되었다. 직접 웹사이트를 만들고 사용자 인터페이스를 디자인하는 일이 재미있고 보람찼다.",
    "나는 매일 새로운 기술을 배우기 위해 노력하고 있다. 온라인 강의를 듣거나, 프로젝트를 만들어보기도 한다. 오픈소스 프로젝트에도 참여해 보았다. 그 과정에서 많은 사람들과 소통하고 협업하는 법을 배웠다. 실력이 부족할 때도 있었지만, 포기하지 않고 계속 도전했다.",
    "졸업 후 나는 IT 회사에 취직하고 싶다. 특히 사용자 중심의 웹 서비스를 만드는 회사에서 일하고 싶다. 사람들에게 편리함을 주는 서비스를 만들고 싶기 때문이다. 또한 해외에서 일하는 것도 나의 목표 중 하나이다. 외국어 공부도 병행하면서 글로벌 개발자가 되고 싶다.",
    "미래에는 나만의 스타트업을 창업하고 싶다. 작지만 의미 있는 서비스를 만들고, 사회에 긍정적인 영향을 주고 싶다. 혼자서는 어려울 수 있지만, 좋은 팀원들과 함께라면 가능할 것이라고 믿는다. 끊임없이 배우고, 성장하는 개발자가 되기 위해 나는 지금도 노력하고 있다. 실패가 두렵지 않다.",
    "실패는 오히려 나를 성장하게 만드는 기회라고 생각한다. 그래서 어떤 일이든 도전하고 싶다. 내 꿈을 이루기 위해 필요한 것은 끈기와 열정이다. 가끔 지치기도 하지만, 내가 가고자 하는 길을 생각하면 다시 힘이 난다. 가족과 친구들의 응원도 큰 힘이 된다.",
    "앞으로도 나는 목표를 향해 열심히 걸어갈 것이다. 지금은 아직 부족하지만, 언젠가는 나의 꿈을 이룰 수 있을 것이라 믿는다. 매일 조금씩 발전하며 더 나은 사람이 되고 싶다. 꿈은 멀리 있는 것이 아니라, 노력 속에 있다는 것을 나는 안다. 그래서 오늘도 나는 열심히 공부하고, 도전한다."
]

# Sample data for each language
english_samples = [
    "The weather is beautiful today.",
    "I love programming and machine learning.",
    "What time is the meeting tomorrow?",
    "Can you help me with this problem?",
    "The new restaurant has excellent food.",
    "I'm learning Python programming.",
    "The movie was really interesting.",
    "How was your weekend?",
    "I need to finish this project soon.",
    "The book is on the table.",
    "She speaks three languages fluently.",
    "The concert starts at 8 PM.",
    "I'm looking forward to the holidays.",
    "The computer needs to be repaired.",
    "What's your favorite color?",
    "The train arrives in 10 minutes.",
    "I enjoy reading science fiction.",
    "The garden needs watering.",
    "Can you pass me the salt?",
    "The weather forecast predicts rain.",
    "I'm going to the gym later.",
    "The presentation was successful.",
    "What's your phone number?",
    "The coffee is too hot.",
    "I need to buy groceries.",
    "The movie theater is crowded.",
    "How do you spell your name?",
    "The museum is closed on Mondays.",
    "I'm studying for my exam.",
    "The restaurant is fully booked.",
    "What's the capital of France?",
    "The traffic is heavy today.",
    "I'm learning to play guitar.",
    "The library has many books.",
    "Can you speak more slowly?",
    "The weather is getting colder.",
    "I'm going to visit my family.",
    "The meeting starts in 5 minutes.",
    "What's your favorite movie?",
    "The computer is running slowly.",
    "I need to make a phone call.",
    "The park is beautiful in spring.",
    "How long is the movie?",
    "The restaurant serves good food.",
    "I'm looking for my keys.",
    "The train is delayed.",
    "What's your email address?",
    "The weather is perfect today.",
    "I'm going to the beach.",
    "The book is very interesting.",
    "Last weekend, I visited a newly opened restaurant near my home with some of my friends. The weather was absolutely delightful – it was bright and sunny, making it the perfect day to enjoy a meal outdoors. We had a fantastic time, and the cuisine was simply exquisite. I opted for a pasta dish, which was rich in flavor and wonderfully prepared. My companions also sampled some traditional dishes, and they were blown away by the flavors and the meticulous presentation. After our meal, we decided to take a leisurely stroll through a nearby park. The air was crisp, and the flowers were in full bloom, creating a serene atmosphere. As we wandered through the park, we chatted about our upcoming projects and how we could enhance our productivity. One of my friends, who is fluent in three languages, suggested that we start learning a new language together. I thought it was an excellent idea, so I immediately agreed to join him. Later, we went to the theater to catch a newly released film, which turned out to be extremely engaging and thought-provoking. We spent the rest of the evening discussing the storyline, the impressive special effects, and the actors' performances. It was an entertaining and fulfilling day. The following day, I dedicated some time at home to prepare for an important meeting scheduled for the afternoon. I had to finalize my presentation, and the pressure was mounting. Fortunately, I managed to wrap it up just in time. The meeting went smoothly, and we successfully covered crucial points regarding the project. Overall, it was a productive and enjoyable weekend.",
    "Have you eaten lunch yet?",
    "The sky is so blue today.",
    "I need to buy new shoes.",
    "Where is the nearest bank?",
    "The music is too loud.",
    "Can you help me find my way?",
    "The flowers are blooming.",
    "What time do you wake up?",
    "I love chocolate ice cream.",
    "The internet is very slow.",
    "She's a talented musician.",
    "The party starts at nine.",
    "Do you speak English?",
    "The water is very cold.",
    "I lost my wallet yesterday.",
    "The birds are singing.",
    "What's your favorite food?",
    "The sun is setting now.",
    "I need a new computer.",
    "The baby is sleeping.",
    "Where did you park your car?",
    "The cake tastes delicious.",
    "I'm feeling tired today.",
    "The window is broken.",
    "What's the weather like?",
    "The door is locked.",
    "I forgot my password.",
    "The grass needs cutting.",
    "Can you repeat that please?",
    "The phone is ringing.",
    "I'm running late today.",
    "The food is still hot.",
    "What's your address?",
    "The cat is sleeping.",
    "I need some fresh air.",
    "The room is too dark.",
    "Where are you from?",
    "The milk is expired.",
    "I have a headache.",
    "The floor is wet.",
    "What day is it today?",
    "The battery is low.",
    "I'm learning to cook.",
    "The stairs are steep.",
    "Can you drive me home?",
    "The movie starts soon.",
    "I need a vacation.",
    "The light is bright.",
    "What's your name?",
    "The door is open.",
    "I'm feeling hungry.",
    "The car won't start.",
    "How old are you?",
    "The wind is strong.",
    "I need some help.",
    "The soup is hot.",
    "What time is it?",
    "The bed is made.",
    "I'm going shopping.",
    "The rain has stopped.",
    "Can you wait here?",
    "The bus is coming.",
    "I need a drink.",
    "The house is clean.",
    "What's happening?",
    "The dog is barking.",
    "I'm feeling sick.",
    "The tea is ready.",
    "How are you today?",
    "The snow is falling.",
    "I need some sleep.",
    "The fire is warm.",
    "What's that noise?",
    "The chair is broken.",
    "I'm going home.",
    "The moon is bright.",
    "Can you see that?",
    "The water is boiling.",
    "I need a break.",
    "The air is fresh.",
    "What's your job?",
    "The road is busy.",
    "I'm feeling happy.",
    "The glass is full.",
    "How was your day?",
    "The night is quiet.",
    "I need some money.",
    "The wall is white.",
    "What's for dinner?",
    "The clock is ticking.",
    "I'm going out.",
    "The sky is dark.",
    "Can you help me?",
    "The paper is blank.",
    "I need a pen.",
    "The tree is tall.",
    "What's wrong?",
    "The door is closed.",
    "I'm staying here.",
    "The sun is bright.",
    "How much is this?",
    "The room is hot.",
    "I need some rest.",
    "The floor is clean."
]

vietnamese_samples = [
    "Hôm nay trời đẹp quá.",
    "Tôi thích lập trình và học máy.",
    "Cuộc họp ngày mai vào lúc mấy giờ?",
    "Bạn có thể giúp tôi với vấn đề này không?",
    "Nhà hàng mới có đồ ăn ngon.",
    "Tôi đang học lập trình Python.",
    "Bộ phim thật thú vị.",
    "Cuối tuần của bạn thế nào?",
    "Tôi cần hoàn thành dự án này sớm.",
    "Quyển sách ở trên bàn.",
    "Cô ấy nói được ba thứ tiếng.",
    "Buổi hòa nhạc bắt đầu lúc 8 giờ tối.",
    "Tôi đang mong chờ kỳ nghỉ.",
    "Máy tính cần được sửa.",
    "Màu yêu thích của bạn là gì?",
    "Tàu sẽ đến trong 10 phút nữa.",
    "Tôi thích đọc truyện khoa học viễn tưởng.",
    "Vườn cần được tưới nước.",
    "Bạn có thể đưa muối cho tôi không?",
    "Dự báo thời tiết nói sẽ mưa.",
    "Tôi sẽ đi tập gym sau.",
    "Buổi thuyết trình rất thành công.",
    "Số điện thoại của bạn là gì?",
    "Cà phê quá nóng.",
    "Tôi cần mua đồ ăn.",
    "Rạp chiếu phim đông người.",
    "Tên bạn đánh vần thế nào?",
    "Bảo tàng đóng cửa vào thứ Hai.",
    "Tôi đang học cho kỳ thi.",
    "Nhà hàng đã hết chỗ.",
    "Thủ đô của Pháp là gì?",
    "Giao thông hôm nay đông.",
    "Tôi đang học chơi guitar.",
    "Thư viện có nhiều sách.",
    "Bạn có thể nói chậm hơn không?",
    "Thời tiết đang lạnh dần.",
    "Tôi sẽ đi thăm gia đình.",
    "Cuộc họp bắt đầu trong 5 phút nữa.",
    "Phim yêu thích của bạn là gì?",
    "Máy tính chạy chậm.",
    "Tôi cần gọi điện thoại.",
    "Công viên đẹp vào mùa xuân.",
    "Phim dài bao lâu?",
    "Nhà hàng phục vụ đồ ăn ngon.",
    "Tôi đang tìm chìa khóa.",
    "Tàu bị trễ.",
    "Địa chỉ email của bạn là gì?",
    "Thời tiết hôm nay thật tuyệt.",
    "Tôi sẽ đi biển.",
    "Quyển sách rất thú vị.",
    # Additional 100 Vietnamese samples
    "Bạn đã ăn cơm chưa?",
    "Bầu trời hôm nay xanh quá.",
    "Tôi cần mua giày mới.",
    "Ngân hàng gần nhất ở đâu?",
    "Nhạc quá to.",
    "Bạn có thể chỉ đường cho tôi không?",
    "Hoa đang nở rộ.",
    "Bạn thức dậy lúc mấy giờ?",
    "Tôi thích kem sô cô la.",
    "Internet rất chậm.",
    "Cô ấy là một nhạc sĩ tài năng.",
    "Bữa tiệc bắt đầu lúc 9 giờ.",
    "Bạn có nói tiếng Anh không?",
    "Nước rất lạnh.",
    "Tôi đánh mất ví hôm qua.",
    "Chim đang hót.",
    "Món ăn yêu thích của bạn là gì?",
    "Mặt trời đang lặn.",
    "Tôi cần một máy tính mới.",
    "Em bé đang ngủ.",
    "Bạn đậu xe ở đâu?",
    "Bánh ngon quá.",
    "Hôm nay tôi thấy mệt.",
    "Cửa sổ bị vỡ.",
    "Thời tiết thế nào?",
    "Cửa đã khóa.",
    "Tôi quên mật khẩu rồi.",
    "Cỏ cần cắt.",
    "Bạn có thể nhắc lại được không?",
    "Điện thoại đang reo.",
    "Hôm nay tôi đến muộn.",
    "Thức ăn vẫn còn nóng.",
    "Địa chỉ của bạn là gì?",
    "Con mèo đang ngủ.",
    "Tôi cần hít thở không khí trong lành.",
    "Phòng quá tối.",
    "Bạn đến từ đâu?",
    "Sữa đã hết hạn.",
    "Tôi bị đau đầu.",
    "Sàn nhà ướt.",
    "Hôm nay là thứ mấy?",
    "Pin yếu rồi.",
    "Tôi đang học nấu ăn.",
    "Cầu thang dốc quá.",
    "Bạn có thể chở tôi về nhà không?",
    "Phim sắp bắt đầu.",
    "Tôi cần nghỉ ngơi.",
    "Ánh sáng quá chói.",
    "Tên bạn là gì?",
    "Cửa đang mở.",
    "Tôi đang đói.",
    "Xe không nổ máy.",
    "Bạn bao nhiêu tuổi?",
    "Gió rất mạnh.",
    "Tôi cần giúp đỡ.",
    "Súp còn nóng.",
    "Mấy giờ rồi?",
    "Giường đã được dọn.",
    "Tôi đi mua sắm đây.",
    "Mưa đã ngừng.",
    "Bạn có thể đợi ở đây không?",
    "Xe buýt đang đến.",
    "Tôi cần uống nước.",
    "Nhà sạch sẽ quá.",
    "Chuyện gì đang xảy ra vậy?",
    "Chó đang sủa.",
    "Tôi cảm thấy không khỏe.",
    "Trà đã pha xong.",
    "Hôm nay bạn thế nào?",
    "Tuyết đang rơi.",
    "Tôi cần ngủ một chút.",
    "Lửa ấm quá.",
    "Tiếng ồn gì vậy?",
    "Ghế bị gãy rồi.",
    "Tôi về nhà đây.",
    "Trăng sáng quá.",
    "Bạn có thấy cái đó không?",
    "Nước đang sôi.",
    "Tôi cần nghỉ giải lao.",
    "Không khí trong lành quá.",
    "Công việc của bạn là gì?",
    "Đường đông quá.",
    "Tôi cảm thấy vui.",
    "Ly đã đầy.",
    "Hôm nay bạn thế nào?",
    "Đêm yên tĩnh quá.",
    "Tôi cần tiền.",
    "Tường màu trắng.",
    "Tối nay ăn gì?",
    "Đồng hồ đang chạy.",
    "Tôi đi ra ngoài đây.",
    "Trời tối quá.",
    "Bạn có thể giúp tôi không?",
    "Tờ giấy trắng.",
    "Tôi cần một cây bút.",
    "Cây cao quá.",
    "Có chuyện gì vậy?",
    "Cửa đóng rồi.",
    "Tôi ở lại đây.",
    "Nắng chói quá.",
    "Cái này giá bao nhiêu?",
    "Phòng nóng quá.",
    "Tôi cần nghỉ ngơi.",
    "Sàn nhà sạch sẽ."
    "Tôi đang đọc sách."
    "Từ khi còn nhỏ, tôi đã mơ ước trở thành một nhà văn. Mỗi buổi tối sau khi học bài xong, tôi thường ngồi bên cửa sổ, lắng nghe tiếng mưa rơi và viết những câu chuyện tưởng tượng về thế giới kỳ diệu. Dù chỉ là những mẩu truyện ngắn đơn giản, nhưng chúng giúp tôi nuôi dưỡng trí tưởng tượng và khả năng diễn đạt ngôn ngữ. Càng lớn, tôi càng nhận ra rằng viết không chỉ là thể hiện suy nghĩ, mà còn là cách để kết nối tâm hồn với người đọc.",
    "Năm ngoái, tôi tham gia một cuộc thi viết truyện ngắn cấp toàn quốc. Ban đầu, tôi khá lo lắng vì không biết liệu bài viết của mình có đủ sâu sắc và cuốn hút hay không. Tuy nhiên, nhờ sự góp ý từ thầy cô và bạn bè, tôi chỉnh sửa nhiều lần và cuối cùng đã đạt giải nhì. Đó là một bước ngoặt quan trọng, khiến tôi tin tưởng hơn vào khả năng của bản thân. Tôi hiểu rằng để tiến bộ, không thể thiếu sự kiên trì, học hỏi và không ngại sửa sai.",
    "Hiện tại, ngoài giờ học ở trường, tôi dành thời gian viết blog và cộng tác với một tạp chí tuổi teen. Tôi luôn cố gắng thử nghiệm những phong cách viết mới, học hỏi từ các tác giả nổi tiếng và không ngừng luyện tập. Với tôi, mỗi câu chữ là một hạt giống, nếu được chăm sóc đúng cách, sẽ nở thành những bông hoa đẹp trong tâm trí người đọc."
]

french_samples = [
    "Le temps est magnifique aujourd'hui.",
    "J'aime la programmation et l'apprentissage automatique.",
    "À quelle heure est la réunion demain?",
    "Pouvez-vous m'aider avec ce problème?",
    "Le nouveau restaurant a une excellente cuisine.",
    "J'apprends la programmation Python.",
    "Le film était vraiment intéressant.",
    "Comment était votre weekend?",
    "Je dois terminer ce projet bientôt.",
    "Le livre est sur la table.",
    "Elle parle couramment trois langues.",
    "Le concert commence à 20h.",
    "J'ai hâte aux vacances.",
    "L'ordinateur doit être réparé.",
    "Quelle est votre couleur préférée?",
    "Le train arrive dans 10 minutes.",
    "J'aime lire la science-fiction.",
    "Le jardin a besoin d'être arrosé.",
    "Pouvez-vous me passer le sel?",
    "La météo prévoit de la pluie.",
    "Je vais à la salle de sport plus tard.",
    "La présentation a été un succès.",
    "Quel est votre numéro de téléphone?",
    "Le café est trop chaud.",
    "Je dois faire les courses.",
    "Le cinéma est bondé.",
    "Comment épelez-vous votre nom?",
    "Le musée est fermé le lundi.",
    "J'étudie pour mon examen.",
    "Le restaurant est complet.",
    "Quelle est la capitale de la France?",
    "La circulation est dense aujourd'hui.",
    "J'apprends à jouer de la guitare.",
    "La bibliothèque a beaucoup de livres.",
    "Pouvez-vous parler plus lentement?",
    "Le temps devient plus froid.",
    "Je vais rendre visite à ma famille.",
    "La réunion commence dans 5 minutes.",
    "Quel est votre film préféré?",
    "L'ordinateur est lent.",
    "Je dois passer un coup de fil.",
    "Le parc est beau au printemps.",
    "Combien de temps dure le film?",
    "Le restaurant sert une bonne cuisine.",
    "Je cherche mes clés.",
    "Le train est en retard.",
    "Quelle est votre adresse email?",
    "Le temps est parfait aujourd'hui.",
    "Je vais à la plage.",
    "Le livre est très intéressant.",
    # Additional 100 French samples
    "Avez-vous déjà mangé?",
    "Le ciel est très bleu aujourd'hui.",
    "J'ai besoin d'acheter de nouvelles chaussures.",
    "Où est la banque la plus proche?",
    "La musique est trop forte.",
    "Pouvez-vous m'aider à trouver mon chemin?",
    "Les fleurs sont en train de fleurir.",
    "À quelle heure vous réveillez-vous?",
    "J'adore la glace au chocolat.",
    "L'internet est très lent.",
    "Elle est une musicienne talentueuse.",
    "La fête commence à neuf heures.",
    "Parlez-vous anglais?",
    "L'eau est très froide.",
    "J'ai perdu mon portefeuille hier.",
    "Les oiseaux chantent.",
    "Quel est votre plat préféré?",
    "Le soleil se couche maintenant.",
    "J'ai besoin d'un nouvel ordinateur.",
    "Le bébé dort.",
    "Où avez-vous garé votre voiture?",
    "Le gâteau est délicieux.",
    "Je me sens fatigué aujourd'hui.",
    "La fenêtre est cassée.",
    "Quel temps fait-il?",
    "La porte est verrouillée.",
    "J'ai oublié mon mot de passe.",
    "L'herbe doit être coupée.",
    "Pouvez-vous répéter s'il vous plaît?",
    "Le téléphone sonne.",
    "Je suis en retard aujourd'hui.",
    "La nourriture est encore chaude.",
    "Quelle est votre adresse?",
    "Le chat dort.",
    "J'ai besoin d'air frais.",
    "La pièce est trop sombre.",
    "D'où venez-vous?",
    "Le lait est périmé.",
    "J'ai mal à la tête.",
    "Le sol est mouillé.",
    "Quel jour sommes-nous?",
    "La batterie est faible.",
    "J'apprends à cuisiner.",
    "Les escaliers sont raides.",
    "Pouvez-vous me conduire à la maison?",
    "Le film commence bientôt.",
    "J'ai besoin de vacances.",
    "La lumière est brillante.",
    "Comment vous appelez-vous?",
    "La porte est ouverte.",
    "J'ai faim.",
    "La voiture ne démarre pas.",
    "Quel âge avez-vous?",
    "Le vent est fort.",
    "J'ai besoin d'aide.",
    "La soupe est chaude.",
    "Quelle heure est-il?",
    "Le lit est fait.",
    "Je vais faire du shopping.",
    "La pluie s'est arrêtée.",
    "Pouvez-vous attendre ici?",
    "Le bus arrive.",
    "J'ai besoin d'une boisson.",
    "La maison est propre.",
    "Que se passe-t-il?",
    "Le chien aboie.",
    "Je me sens malade.",
    "Le thé est prêt.",
    "Comment allez-vous aujourd'hui?",
    "La neige tombe.",
    "J'ai besoin de dormir.",
    "Le feu est chaud.",
    "Quel est ce bruit?",
    "La chaise est cassée.",
    "Je rentre à la maison.",
    "La lune est brillante.",
    "Pouvez-vous voir ça?",
    "L'eau bout.",
    "J'ai besoin d'une pause.",
    "L'air est frais.",
    "Quel est votre métier?",
    "La route est très fréquentée.",
    "Je me sens heureux.",
    "Le verre est plein.",
    "Comment s'est passée votre journée?",
    "La nuit est calme.",
    "J'ai besoin d'argent.",
    "Le mur est blanc.",
    "Qu'y a-t-il pour le dîner?",
    "L'horloge fait tic-tac.",
    "Je sors.",
    "Le ciel est sombre.",
    "Pouvez-vous m'aider?",
    "Le papier est vierge.",
    "J'ai besoin d'un stylo.",
    "L'arbre est grand.",
    "Qu'est-ce qui ne va pas?",
    "La porte est fermée.",
    "Je reste ici.",
    "Le soleil est brillant.",
    "Combien ça coûte?",
    "La pièce est chaude.",
    "J'ai besoin de repos.",
    "Le sol est propre.",
    "Aujourd'hui, le temps est vraiment magnifique. Il fait beau, mais un peu frais, ce qui est parfait pour une promenade. Je me suis levé tôt ce matin pour faire du jogging avant le petit déjeuner. En rentrant, j'ai pris une douche rapide et j'ai préparé un café. Ensuite, j'ai commencé à travailler sur un projet important que je dois rendre demain. Il y a beaucoup de choses à faire, mais je suis confiant que je vais tout finir à temps.",
    "Cet après-midi, je vais retrouver mes amis au café. Nous avons l'habitude de nous y retrouver chaque semaine pour discuter de tout et de rien. J'adore parler avec eux, car ils ont des opinions intéressantes sur divers sujets. Hier, nous avons parlé de la politique, de l'environnement, et même de l'avenir de la technologie. Ils m'ont aussi parlé d'un nouveau restaurant qui a ouvert en ville, et je suis très curieux de l'essayer ce week-end.",
    "D'ailleurs, ce week-end, je vais aller à la montagne avec ma famille. Nous avons réservé une maison près d'un lac, et je suis impatient de passer du temps dans la nature. J'espère qu'il fera encore beau, mais si jamais il pleut, nous pourrons toujours jouer à des jeux de société à l'intérieur. C'est une tradition familiale, et j'adore ces moments-là.",
    "Par ailleurs, je suis en train d'apprendre à jouer de la guitare. Je prends des cours depuis quelques mois et j'ai déjà appris à jouer quelques morceaux. Cependant, il y a encore beaucoup à améliorer, surtout ma technique de doigts. Je me suis fixé comme objectif de jouer une chanson entière d'ici la fin de l'année, et je suis déterminé à y arriver.",
    "Enfin, je dois mentionner que j'ai un examen de français la semaine prochaine. C'est un peu stressant, mais je pense que si je révise bien, je pourrai réussir. J'ai déjà étudié la grammaire, le vocabulaire et les conjugaisons, donc je me sens plutôt prêt. Cependant, il y a encore quelques points que je dois réviser, surtout les verbes irréguliers et les prépositions. Je vais aussi essayer de m'entraîner à parler un peu plus, car la partie orale est la plus difficile pour moi.",
]

japanese_samples = [
    "今日は天気がとても良いです。",
    "プログラミングと機械学習が大好きです。",
    "明日の会議は何時からですか？",
    "この問題を手伝っていただけますか？",
    "新しいレストランは料理が美味しいです。",
    "Pythonプログラミングを勉強しています。",
    "映画はとても面白かったです。",
    "週末はどうでしたか？",
    "このプロジェクトを早く終わらせる必要があります。",
    "本は机の上にあります。",
    "彼女は3つの言語を流暢に話せます。",
    "コンサートは8時から始まります。",
    "休暇が待ち遠しいです。",
    "コンピュータを修理する必要があります。",
    "好きな色は何ですか？",
    "電車は10分後に到着します。",
    "SF小説を読むのが好きです。",
    "庭に水をやる必要があります。",
    "塩を取っていただけますか？",
    "天気予報では雨が降るそうです。",
    "後でジムに行きます。",
    "プレゼンテーションは成功でした。",
    "電話番号を教えていただけますか？",
    "コーヒーが熱すぎます。",
    "食料品を買う必要があります。",
    "映画館は混雑しています。",
    "お名前のスペルを教えていただけますか？",
    "美術館は月曜日は休館です。",
    "試験勉強をしています。",
    "レストランは予約でいっぱいです。",
    "フランスの首都はどこですか？",
    "今日は交通が混雑しています。",
    "ギターを習っています。",
    "図書館には多くの本があります。",
    "もう少しゆっくり話していただけますか？",
    "天気が寒くなってきました。",
    "家族に会いに行きます。",
    "会議は5分後に始まります。",
    "好きな映画は何ですか？",
    "コンピュータの動作が遅いです。",
    "電話をかけなければなりません。",
    "春の公園は美しいです。",
    "映画はどのくらいの長さですか？",
    "レストランは美味しい料理を提供しています。",
    "鍵を探しています。",
    "電車が遅れています。",
    "メールアドレスを教えていただけますか？",
    "今日は天気が完璧です。",
    "海に行きます。",
    "本はとても面白いです。",
    "最近、私は新しいプロジェクトに取り組んでいます。このプロジェクトは、会社の重要な課題を解決するために始められました。最初は少し不安でしたが、チームのみんなと協力しながら進めているので、だんだん自信がついてきました。プロジェクトの成功には、チームワークとコミュニケーションが欠かせません。",
    "もう食事はしましたか？",
    "今日は空が青いですね。",
    "新しい靴を買う必要があります。",
    "最寄りの銀行はどこですか？",
    "音楽が大きすぎます。",
    "道案内をしていただけますか？",
    "花が咲いています。",
    "何時に起きますか？",
    "チョコレートアイスが大好きです。",
    "インターネットが遅いです。",
    "彼女は才能のある音楽家です。",
    "パーティーは9時から始まります。",
    "英語を話せますか？",
    "水がとても冷たいです。",
    "昨日財布をなくしました。",
    "鳥が鳴いています。",
    "好きな食べ物は何ですか？",
    "日が沈んでいます。",
    "新しいパソコンが必要です。",
    "赤ちゃんが寝ています。",
    "車をどこに停めましたか？",
    "ケーキが美味しいです。",
    "今日は疲れています。",
    "窓が割れています。",
    "天気はどうですか？",
    "ドアが鍵がかかっています。",
    "パスワードを忘れました。",
    "芝生を刈る必要があります。",
    "もう一度言っていただけますか？",
    "電話が鳴っています。",
    "今日は遅刻です。",
    "食べ物がまだ熱いです。",
    "住所を教えてください。",
    "猫が寝ています。",
    "新鮮な空気が必要です。",
    "部屋が暗すぎます。",
    "出身はどちらですか？",
    "牛乳の賞味期限が切れています。",
    "頭が痛いです。",
    "床が濡れています。",
    "今日は何曜日ですか？",
    "バッテリーが少なくなっています。",
    "料理を習っています。",
    "階段が急です。",
    "家まで送っていただけますか？",
    "映画がもうすぐ始まります。",
    "休暇が必要です。",
    "光が明るいです。",
    "お名前は何ですか？",
    "ドアが開いています。",
    "お腹が空きました。",
    "車がエンジンがかかりません。",
    "おいくつですか？",
    "風が強いです。",
    "助けが必要です。",
    "スープが熱いです。",
    "何時ですか？",
    "ベッドが整っています。",
    "買い物に行きます。",
    "雨が止みました。",
    "ここで待っていただけますか？",
    "バスが来ています。",
    "飲み物が必要です。",
    "家がきれいです。",
    "何が起こっているのですか？",
    "犬が吠えています。",
    "具合が悪いです。",
    "お茶が入りました。",
    "今日の調子はどうですか？",
    "雪が降っています。",
    "少し寝る必要があります。",
    "火が暖かいです。",
    "その音は何ですか？",
    "椅子が壊れています。",
    "家に帰ります。",
    "月が明るいです。",
    "それが見えますか？",
    "お湯が沸いています。",
    "休憩が必要です。",
    "空気が新鮮です。",
    "お仕事は何ですか？",
    "道が混んでいます。",
    "幸せです。",
    "グラスがいっぱいです。",
    "今日はどうでしたか？",
    "夜が静かです。",
    "お金が必要です。",
    "壁が白いです。",
    "夕食は何ですか？",
    "時計が動いています。",
    "本はとても面白いです。",
    "毎日、朝9時にオフィスに到着し、まずはメールを確認します。それから、午前中は会議が多く、午後には報告書を作成することが主な仕事です。今週は特に忙しく、プロジェクトの進捗状況を上司に報告するための資料を準備しなければならないので、かなりのプレッシャーを感じています。しかし、仕事を終えるときの達成感は何にも代えがたいものがあります。",
    "私の仕事のスタイルは、計画的に物事を進めることです。もちろん、時には予定通りに進まないこともありますが、その場合でも柔軟に対応し、問題を解決することが大切だと考えています。また、私は仕事だけでなく、プライベートの時間も大切にしています。週末は家族や友人と過ごすことが多く、リフレッシュするためにアウトドアに出かけることもあります。",
    "最近、天気も良くて、週末に公園でピクニックをするのが楽しみです。今のところ、来週の土曜日は晴れる予報ですので、その日を楽しみにしています。天気が良ければ、家族全員で一緒に出かける予定です。それに加えて、私は最近料理にも挑戦しており、今度は新しいレシピを試してみようと思っています。",
    "それでも、まだやるべきことがたくさんあります。次の月曜日には、プロジェクトの最終報告会がありますので、準備を怠らないようにしたいと思います。今はそのことが頭から離れませんが、時間をうまく使って、仕事もプライベートも充実させることが目標です。",
]

def save_samples(filename, samples):
    with open(filename, 'w', encoding='utf-8') as f:
        for sample in samples:
            f.write(sample + '\n')

def main():
    # Create data directory if it doesn't exist
    os.makedirs('data', exist_ok=True)
    
    # Save samples for each language
    save_samples('data/en.txt', english_samples)
    save_samples('data/vi.txt', vietnamese_samples)
    save_samples('data/fr.txt', french_samples)
    save_samples('data/jp.txt', japanese_samples)
    save_samples('data/de.txt', german_samples)  
    save_samples('data/es.txt', spanish_samples)  
    save_samples('data/ko.txt', korean_samples)   
    
    
    print("Sample data has been generated successfully!")

if __name__ == "__main__":
    main() 